name: CI

on:
  push:
    branches: [main, develop, test-pipeline]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4

      - name: Configurar JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Compilar y ejecutar tests
        run: mvn clean verify
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET_TEST }}

      - name: Subir JAR como artifact
        uses: actions/upload-artifact@v4
        with:
          name: gamification-service-jar
          path: target/*.jar
          retention-days: 14

      - name: Subir reporte JaCoCo
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/
          retention-days: 14

      - name: Subir resultados Surefire
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports/
          retention-days: 14
